# Base shared config. Always combine with an override file:
#   Staging:    docker compose -f docker-compose.yml -f docker-compose.staging.yml up
#   Production: docker compose -f docker-compose.yml -f docker-compose.prod.yml up --build

# to run individual container
#  docker compose -f docker-compose.yml -f docker-compose.prod.yml up --build -d maypila-ui
#  docker compose -f docker-compose.yml -f docker-compose.prod.yml up --build -d maypila-api

services:

  maypila-ui:
    container_name: maypila-ui
    build:
      context: ./maypila-vue-ui
    networks:
      - web-network

  maypila-api:
    container_name: maypila-api
    build:
      context: ./maypila-backend-api
    networks:
      - web-network

networks:
  web-network:
    external: true